# Generated by Django 5.1.2 on 2024-11-16 10:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=15)),
                ('company_name', models.CharField(blank=True, max_length=255)),
                ('owner_name', models.CharField(blank=True, max_length=255)),
                ('new_order_notifications', models.BooleanField(default=True)),
                ('order_status_notifications', models.BooleanField(default=True)),
                ('financial_notifications', models.BooleanField(default=True)),
                ('telegram_connected', models.BooleanField(default=False)),
                ('telegram_chat_id', models.CharField(blank=True, max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
