# Generated by Django 5.1.2 on 2024-11-13 14:16

import django.db.models.deletion
import goods.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100, unique=True, verbose_name='Категория')),
                ('category_icon', models.CharField(default='fas fa-box', max_length=100, verbose_name='иконка')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='PhoneModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_name', models.CharField(max_length=100, unique=True, verbose_name='Модель телефона')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone_models', to='goods.category')),
            ],
            options={
                'verbose_name': 'Модель телефона',
                'verbose_name_plural': 'Модели телефона',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('custom_discount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Индивидуальная скидка')),
                ('quantity', models.PositiveIntegerField()),
                ('product_url', models.URLField(blank=True, null=True, verbose_name='URL страницы товара')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qr_codes/')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_front', models.ImageField(blank=True, null=True, upload_to=goods.models.user_directory_path)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='goods.product')),
            ],
            options={
                'verbose_name': 'Изображение продукта',
                'verbose_name_plural': 'Изображения продуктов',
            },
        ),
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100, unique=True, verbose_name='Называние модель')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='goods.phonemodel')),
            ],
            options={
                'verbose_name': 'Называние модель',
                'verbose_name_plural': 'Называние модели',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.productmodel'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['product_name', 'author'], name='goods_produ_product_40ff85_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('product_name', 'author')},
        ),
    ]
